name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: HEMTT Build
        uses: docker://hemtt/hemtt:0.6.1
        with:
          entrypoint: hemtt
          args: build --release

      - name: Upload mod
        uses: actions/upload-artifact@v1
        with:
          name: '@anrop_cwr3_tfar_compat'
          path: releases/1.0.0/@anrop_cwr3_tfar_compat
